// Chef-authored recipe knowledge for Shake Shake Fresh Noodle.
//
// This file trains Benu (the AI menu assistant) on the exact composition of
// every dish. The data is consumed by the system prompt builder in
// app/api/chat/route.ts and given to the model alongside the menu listing,
// so the assistant can answer granular ingredient / allergen / customization
// questions instead of relying only on the dish tags.
//
// House components (hand-pulled noodles, chili oil, soy braise master sauce,
// braised meats, dumpling wrappers, scallion pancakes, beef bone broth) are
// defined once and referenced by ID inside each dish. When the guest asks
// "is there sesame in the wontons?" the model is expected to expand the
// referenced house_chili_oil component and answer correctly.
//
// Dishes are keyed to the live menu via the `menuName` field, which MUST
// exactly match `MenuItem.name` in lib/menu.ts so the model can cite the
// right card.

export type HouseComponent = {
  name: string;
  description: string;
  ingredients: string[];
  allergens: string[];
  spiceLevel?: string;
};

export type Recipe = {
  id: string;
  // Exact menu name (must match MenuItem.name) so the model can cite the
  // dish card. A recipe may map to several menu items (e.g. the soft drinks
  // recipe covers Coke, Diet Coke, and Sprite).
  menuName: string | string[];
  category:
    | "Appetizers"
    | "Dry Noodles"
    | "Noodle Soup"
    | "Rice"
    | "Beverages";
  // `null` means the recipe price hasn't been confirmed by the kitchen yet
  // (the MENU may still show a tentative price). When null, the assistant
  // is instructed to say it will confirm with the kitchen rather than
  // recite a number — see CUSTOMIZATION_RULES.missing_prices.
  price: number | null;
  priceNote?: string;
  pieceCount?: number;
  spiceOption?: boolean;
  spiceDefault?: string;
  noodleChoice?: string[];
  addOns?: Record<string, number>;
  // Lists ingredient strings as the chef would describe them. House
  // components are referenced by their key in HOUSE_COMPONENTS (e.g.
  // "house_chili_oil") so the model can expand them. Any other entry is a
  // plain ingredient.
  ingredients: string[];
  steps: string[];
  // Top-level allergens at the dish level. These OMIT allergens that live
  // inside referenced house components — the model is told to union both
  // sets when answering allergen questions.
  allergens: string[];
  notes?: string;
};

export const HOUSE_COMPONENTS: Record<string, HouseComponent> = {
  hand_pulled_noodles_round: {
    name: "House Hand Pulled Round Noodles",
    description:
      "Made fresh daily in house. Round profile, chewy bite. High gluten wheat flour, water, salt, small amount of alkaline water (penghui) for elasticity. Rested, hand pulled to order, boiled 60 to 90 seconds.",
    ingredients: [
      "high gluten wheat flour",
      "water",
      "salt",
      "alkaline water (kansui)",
    ],
    allergens: ["wheat", "gluten"],
  },
  hand_pulled_noodles_flat: {
    name: "House Hand Pulled Flat Noodles (Biang Biang style)",
    description:
      "Same dough as round noodles, hand stretched and slapped into wide flat ribbons. Boiled 90 to 120 seconds depending on thickness.",
    ingredients: [
      "high gluten wheat flour",
      "water",
      "salt",
      "alkaline water (kansui)",
    ],
    allergens: ["wheat", "gluten"],
  },
  house_chili_oil: {
    name: "House Chili Oil (la you)",
    description:
      "Signature aromatic chili oil. Neutral oil heated with aromatics, then poured over a blend of crushed Sichuan chilies for layered heat and fragrance.",
    ingredients: [
      "neutral oil (soybean or canola)",
      "crushed Sichuan chili flakes (er jing tiao)",
      "Korean gochugaru (for color)",
      "Sichuan peppercorns",
      "star anise",
      "bay leaves",
      "cassia bark",
      "ginger slices",
      "scallion whites",
      "garlic cloves",
      "white sesame seeds",
      "salt",
      "splash of black vinegar at the end",
    ],
    allergens: ["sesame"],
    spiceLevel: "medium high",
  },
  soy_braise_master_sauce: {
    name: "Soy Braise Master Sauce (lu shui)",
    description:
      "Aromatic master braising liquid reused and refreshed daily. Used for braised beef shank, pork belly, and cold cut beef.",
    ingredients: [
      "light soy sauce",
      "dark soy sauce",
      "Shaoxing wine",
      "rock sugar",
      "ginger",
      "scallion",
      "garlic",
      "star anise",
      "cassia bark",
      "bay leaves",
      "Sichuan peppercorns",
      "dried tangerine peel",
      "fennel seeds",
      "cloves",
      "white pepper",
      "water",
    ],
    allergens: ["soy", "wheat (from soy sauce)"],
  },
  braised_beef_shank: {
    name: "Soy Braised Beef Shank",
    description:
      "Beef shank simmered in the soy braise master sauce for 2 to 3 hours until tender, then rested in liquid. Sliced cold for cold cuts and beef rolls, or warmed and chunked for noodle soups.",
    ingredients: ["beef shank", "soy_braise_master_sauce"],
    allergens: ["soy", "wheat"],
  },
  braised_pork_belly: {
    name: "Red Braised Pork Belly (hong shao rou style)",
    description:
      "Pork belly blanched, then caramelized in rock sugar and braised in master sauce with extra dark soy and Shaoxing wine for color and gloss.",
    ingredients: [
      "skin on pork belly",
      "rock sugar",
      "dark soy sauce",
      "light soy sauce",
      "Shaoxing wine",
      "ginger",
      "scallion",
      "star anise",
      "cassia bark",
      "bay leaves",
      "water",
    ],
    allergens: ["soy", "wheat"],
  },
  beef_bone_broth: {
    name: "Beef Bone Broth",
    description:
      "Beef leg bones and marrow bones simmered 6 to 8 hours with aromatics. The base for House Special Beef Bone Noodle Soup. Skimmed for clarity.",
    ingredients: [
      "beef leg bones",
      "beef marrow bones",
      "ginger",
      "scallion",
      "white onion",
      "Shaoxing wine",
      "white pepper",
      "salt",
      "water",
    ],
    allergens: [],
  },
  dumpling_wrapper: {
    name: "House Dumpling Wrapper",
    description:
      "Simple hand rolled wrapper made from all purpose flour and water. Used for boiled dumplings and chili oil wontons (wonton version is rolled thinner and square cut).",
    ingredients: ["all purpose wheat flour", "water", "pinch of salt"],
    allergens: ["wheat", "gluten"],
  },
  scallion_pancake: {
    name: "Flaky Scallion Pancake (cong you bing)",
    description:
      "Layered laminated dough made by rolling flour and water dough with lard or oil and chopped scallions, then coiling and pan frying to flaky crispness.",
    ingredients: [
      "all purpose wheat flour",
      "hot water",
      "cold water",
      "salt",
      "scallions (finely chopped)",
      "lard or neutral oil",
      "white pepper",
      "five spice powder (small amount)",
    ],
    allergens: ["wheat", "gluten"],
  },
};

export const RECIPES: Recipe[] = [
  {
    id: "popcorn_chicken",
    menuName: "Popcorn Chicken",
    category: "Appetizers",
    price: 11.99,
    spiceOption: true,
    ingredients: [
      "boneless skinless chicken thigh (cut into bite size pieces)",
      "soy sauce",
      "Shaoxing wine",
      "garlic (minced)",
      "ginger (grated)",
      "five spice powder",
      "white pepper",
      "sugar",
      "egg",
      "sweet potato starch (for coating)",
      "neutral frying oil",
      "fresh Thai basil leaves",
      "salt",
      "ground white pepper",
      "five spice powder (finishing dust)",
      "chili powder (optional for spicy version)",
    ],
    steps: [
      "Marinate diced chicken thigh in soy sauce, Shaoxing wine, minced garlic, grated ginger, five spice, white pepper, sugar, and egg for at least 30 minutes.",
      "Dredge marinated chicken thoroughly in sweet potato starch, pressing so each piece gets a craggy coating. Let sit 2 minutes so the starch hydrates.",
      "Heat neutral oil to 325 degrees F. Fry chicken in batches for about 3 minutes until just cooked through. Remove and rest 1 minute.",
      "Raise oil to 375 degrees F. Double fry chicken for 60 to 90 seconds until deep golden and crispy.",
      "In the last 10 seconds, toss a handful of fresh Thai basil leaves into the oil until crisp and translucent.",
      "Drain chicken and basil. Immediately toss in a bowl with salt, white pepper, and five spice powder. Add chili powder for the spicy version.",
      "Serve in a paper lined basket with crispy basil scattered on top.",
    ],
    allergens: ["soy", "wheat (from soy sauce)", "egg"],
  },
  {
    id: "garlic_cucumber",
    menuName: "Garlic Cucumber",
    category: "Appetizers",
    price: 8.99,
    spiceOption: false,
    ingredients: [
      "Persian or English cucumbers",
      "kosher salt",
      "garlic cloves (minced)",
      "light soy sauce",
      "Chinese black vinegar (Chinkiang)",
      "toasted sesame oil",
      "sugar",
      "small amount of house chili oil (optional)",
      "cilantro (optional)",
    ],
    steps: [
      "Smash cucumbers with the flat of a cleaver until they split lengthwise, then tear or cut into rough bite size pieces.",
      "Toss cucumber with kosher salt and let sit 15 minutes to draw out water.",
      "Drain off the released liquid and pat cucumbers dry.",
      "In a bowl whisk minced garlic, light soy sauce, black vinegar, sesame oil, and a touch of sugar.",
      "Toss dressed cucumbers right before serving so they stay crunchy. Optional drizzle of house chili oil and a few cilantro leaves on top.",
    ],
    allergens: ["soy", "wheat (from soy sauce)", "sesame"],
  },
  {
    id: "yuba_celery_salad",
    menuName: "Yuba with Celery Salad",
    category: "Appetizers",
    price: 8.99,
    spiceOption: false,
    ingredients: [
      "dried tofu skin (yuba sticks or sheets, rehydrated)",
      "Chinese celery (or regular celery sliced thin on a bias)",
      "light soy sauce",
      "toasted sesame oil",
      "salt",
      "white sugar (pinch)",
      "garlic (minced, optional)",
      "toasted white sesame seeds",
    ],
    steps: [
      "Soak dried yuba in cool water for 2 to 4 hours until fully pliable, then blanch in boiling water for 30 seconds and shock in ice water.",
      "Cut yuba into 2 inch ribbons or bite size pieces.",
      "Blanch celery slices for 10 seconds, shock in ice water, drain well.",
      "Combine yuba and celery in a bowl with light soy sauce, sesame oil, salt, and a pinch of sugar. Add a touch of minced garlic if desired.",
      "Toss gently, finish with toasted sesame seeds. Serve cold.",
    ],
    allergens: ["soy", "wheat (from soy sauce)", "sesame"],
  },
  {
    id: "chili_oil_wontons",
    menuName: "Chili Oil Wontons (8 pc)",
    category: "Appetizers",
    price: 11.99,
    pieceCount: 8,
    spiceOption: false,
    spiceDefault: "spicy",
    ingredients: [
      "dumpling_wrapper (rolled thin and cut into 3 inch squares)",
      "ground pork (around 20 percent fat)",
      "ginger (grated)",
      "scallion (finely minced)",
      "light soy sauce",
      "Shaoxing wine",
      "white pepper",
      "sesame oil",
      "salt",
      "small amount of cold water or stock (to whip into filling)",
      "house_chili_oil (generous)",
      "light soy sauce (sauce)",
      "Chinese black vinegar",
      "minced garlic (raw)",
      "sugar (pinch)",
      "ground roasted Sichuan peppercorn",
      "chopped scallion greens (garnish)",
      "toasted sesame seeds (garnish)",
    ],
    steps: [
      "Make filling: mix ground pork with grated ginger, minced scallion, soy sauce, Shaoxing wine, white pepper, sesame oil, and salt. Whip in a splash of cold water until the filling is sticky and bouncy.",
      "Place a small teaspoon of filling in the center of each wonton square. Fold corner to corner into a triangle, then bring the two long points together and pinch to seal (chao shou or 'folded arms' shape).",
      "Boil wontons in plenty of water for about 3 to 4 minutes until they float and the wrappers are translucent.",
      "While wontons cook, build the sauce in a serving bowl: house chili oil, light soy sauce, black vinegar, raw minced garlic, a pinch of sugar, and ground Sichuan peppercorn.",
      "Drain wontons gently and place into the sauce bowl. Spoon sauce over the top.",
      "Garnish with chopped scallion greens and toasted sesame seeds.",
    ],
    allergens: ["wheat", "gluten", "soy", "sesame", "pork"],
  },
  {
    id: "pork_cabbage_dumplings",
    menuName: "Pork and Cabbage Boiled Dumplings (12 pc)",
    category: "Appetizers",
    price: 15.99,
    pieceCount: 12,
    spiceOption: false,
    ingredients: [
      "dumpling_wrapper (round, hand rolled)",
      "ground pork (around 25 percent fat)",
      "napa cabbage (finely minced, salted, squeezed dry)",
      "scallion (finely minced)",
      "ginger (grated)",
      "light soy sauce",
      "dark soy sauce (small amount, for color)",
      "Shaoxing wine",
      "sesame oil",
      "white pepper",
      "salt",
      "sugar (pinch)",
      "cold chicken stock or water (to whip into filling)",
      "dipping sauce: black vinegar, light soy sauce, ginger slivers, optional house chili oil",
    ],
    steps: [
      "Mince napa cabbage finely, salt it, let sit 15 minutes, then squeeze out as much water as possible.",
      "Mix ground pork with ginger, scallion, both soy sauces, Shaoxing wine, sesame oil, white pepper, salt, and a pinch of sugar. Whip in cold stock until the filling is sticky and holds together.",
      "Fold in the squeezed napa cabbage. Do not overmix.",
      "Place a tablespoon of filling in the center of each round wrapper. Wet the edge, fold in half, and pleat one side (around 5 to 7 pleats) to seal into a crescent.",
      "Boil dumplings in a large pot of water. When the water returns to a boil, add a cup of cold water. Repeat this twice more (the 'three water' method). Dumplings are done when they float fully and the wrappers look slightly translucent.",
      "Drain and serve with a small dish of black vinegar, light soy sauce, ginger slivers, and optional chili oil.",
    ],
    allergens: ["wheat", "gluten", "soy", "sesame", "pork"],
  },
  {
    id: "house_beef_roll",
    menuName: "House Beef Roll",
    category: "Appetizers",
    price: 12.99,
    spiceOption: true,
    ingredients: [
      "scallion_pancake (cooked, kept warm)",
      "braised_beef_shank (sliced thin)",
      "hoisin sauce",
      "scallion (julienned, white and light green parts)",
      "fresh cilantro sprigs",
      "house_chili_oil (optional, for spicy version)",
      "toasted sesame seeds (optional)",
    ],
    steps: [
      "Cook a scallion pancake until golden, crispy on the outside, and flaky inside. Keep warm.",
      "Lay the pancake flat. Spread a thin even layer of hoisin sauce across the surface.",
      "Arrange overlapping slices of cold or just warmed braised beef shank across the pancake.",
      "Add a generous bundle of julienned scallions and fresh cilantro along one edge.",
      "For the spicy version, drizzle house chili oil over the beef before rolling.",
      "Roll the pancake tightly around the filling like a wrap. Slice on a sharp diagonal into 4 to 6 pieces.",
      "Arrange cut side up on a plate, optional sprinkle of toasted sesame seeds.",
    ],
    allergens: ["wheat", "gluten", "soy", "sesame"],
  },
  {
    id: "house_cold_cut_beef",
    menuName: "House Cold Cut Beef",
    category: "Appetizers",
    price: 12.99,
    spiceOption: false,
    spiceDefault: "with chili oil drizzle",
    ingredients: [
      "braised_beef_shank (chilled overnight in the master sauce)",
      "house_chili_oil",
      "light soy sauce (small splash)",
      "Chinese black vinegar (small splash)",
      "raw garlic (minced)",
      "scallion greens (chopped)",
      "cilantro (optional)",
      "toasted sesame seeds (optional)",
    ],
    steps: [
      "Chill braised beef shank fully in its master sauce overnight so it firms up for clean slicing.",
      "Slice the cold beef shank against the grain into thin even pieces. Tendon marbling should be visible.",
      "Fan the slices on a plate, overlapping slightly.",
      "Build the sauce: spoon house chili oil over the slices, then a small splash of light soy sauce and black vinegar.",
      "Top with raw minced garlic, chopped scallion greens, optional cilantro, and toasted sesame seeds.",
      "Serve cold.",
    ],
    allergens: ["soy", "wheat", "sesame"],
  },
  {
    id: "chili_oil_potato_salad",
    menuName: "Chili Oil Potato Salad",
    category: "Appetizers",
    price: null,
    priceNote: "Confirm price with kitchen",
    spiceOption: false,
    spiceDefault: "spicy",
    ingredients: [
      "russet or yukon gold potatoes (julienned into thin matchsticks)",
      "white rice vinegar (for soaking)",
      "salt",
      "house_chili_oil",
      "light soy sauce",
      "Chinese black vinegar (Chinkiang)",
      "minced garlic (raw)",
      "ground roasted Sichuan peppercorn",
      "scallion greens (chopped)",
      "cilantro (chopped, optional)",
      "toasted sesame seeds",
      "sugar (small pinch)",
      "dried red chilies (optional, for sizzle finish)",
    ],
    steps: [
      "Peel potatoes and cut into very thin julienned matchsticks (a mandoline helps). Rinse under cold water to remove surface starch.",
      "Soak the julienned potato in cold water with a splash of white vinegar for 10 minutes to keep them crisp and white.",
      "Bring a pot of water to a boil. Blanch the potato matchsticks for 30 to 45 seconds only, they should stay snappy and crunchy, not soft.",
      "Immediately shock the potatoes in ice water to stop cooking. Drain thoroughly and pat dry.",
      "In a serving bowl, combine the potatoes with raw minced garlic, light soy sauce, black vinegar, a small pinch of sugar, salt, and ground Sichuan peppercorn.",
      "Drizzle generously with house chili oil and toss until every strand is coated red.",
      "Finish with chopped scallion greens, optional cilantro, and toasted sesame seeds.",
      "Serve cold or room temperature. The dish should be tangy, numbing, spicy, and crunchy.",
    ],
    allergens: ["soy", "wheat (from soy sauce)", "sesame"],
  },
  {
    id: "chili_oil_flat_noodle_beef_bone",
    menuName: "Chili Oil Flat Noodle with Beef Bone",
    category: "Dry Noodles",
    price: 21.99,
    noodleChoice: ["flat (default)", "round"],
    spiceOption: false,
    spiceDefault: "spicy",
    ingredients: [
      "hand_pulled_noodles_flat",
      "bone in braised beef shank section (with marrow bone, from master sauce)",
      "house_chili_oil",
      "light soy sauce",
      "Chinese black vinegar (small splash)",
      "minced garlic (raw)",
      "scallion (chopped)",
      "ground roasted Sichuan peppercorn",
      "sugar (pinch)",
      "cilantro (optional)",
      "bok choy (blanched, optional side)",
    ],
    steps: [
      "Boil flat hand pulled noodles for 90 to 120 seconds, then drain well.",
      "While noodles cook, warm a bone in braised beef section in the master sauce until heated through.",
      "In the serving bowl, build the dressing: light soy sauce, a splash of black vinegar, raw minced garlic, ground Sichuan peppercorn, a pinch of sugar.",
      "Add hot drained noodles to the bowl. Pour over a generous ladle of house chili oil. Toss at the table or before serving until each strand is glossy red.",
      "Place the bone in braised beef on top of the noodles, marrow side up.",
      "Garnish with chopped scallion and optional cilantro. Serve with blanched bok choy on the side if requested.",
    ],
    allergens: ["wheat", "gluten", "soy", "sesame"],
  },
  {
    id: "regular_chili_oil_flat_noodle",
    menuName: "Regular Chili Oil Flat Noodle",
    category: "Dry Noodles",
    price: 14.99,
    noodleChoice: ["flat (default)", "round"],
    spiceOption: false,
    spiceDefault: "spicy",
    addOns: {
      tomato_eggs: 2.0,
      ground_pork: 3.0,
      braised_beef: 4.0,
    },
    ingredients: [
      "hand_pulled_noodles_flat",
      "house_chili_oil",
      "light soy sauce",
      "Chinese black vinegar",
      "minced garlic (raw)",
      "chopped scallion",
      "ground roasted Sichuan peppercorn",
      "chili flakes (dry, on top)",
      "neutral oil (for the sizzle pour finish)",
      "sugar (pinch)",
      "toasted sesame seeds (optional)",
    ],
    steps: [
      "Boil flat hand pulled noodles for 90 to 120 seconds, drain well, and place in a serving bowl.",
      "Make a small mound on top of the noodles with: chopped scallion, raw minced garlic, dry chili flakes, ground Sichuan peppercorn, and a pinch of sugar.",
      "Heat 2 to 3 tablespoons of neutral oil until lightly smoking. Pour the hot oil directly over the chili flake and garlic mound. It should sizzle and bloom (you po mian moment).",
      "Add light soy sauce and a splash of black vinegar around the edge.",
      "Drizzle additional house chili oil for color and depth.",
      "Toss thoroughly before eating. Optional sesame seeds on top.",
      "If add ons are ordered, prepare separately and place on top: stir fried tomato and egg, sauteed seasoned ground pork, or sliced braised beef from the master sauce.",
    ],
    allergens: ["wheat", "gluten", "soy", "sesame"],
  },
  {
    id: "numbing_spicy_minced_pork_noodle",
    menuName: "Numbing Spicy Minced Pork Noodle",
    category: "Dry Noodles",
    price: 17.99,
    noodleChoice: ["round (default)", "flat"],
    spiceOption: false,
    spiceDefault: "spicy mala",
    ingredients: [
      "hand_pulled_noodles_round",
      "ground pork (medium fat)",
      "Pixian doubanjiang (fermented broad bean chili paste)",
      "sweet bean sauce (tianmianjiang)",
      "light soy sauce",
      "dark soy sauce (small amount)",
      "Shaoxing wine",
      "minced ginger",
      "minced garlic",
      "ground roasted Sichuan peppercorn",
      "house_chili_oil",
      "sugar",
      "neutral oil",
      "scallion (chopped, for finishing)",
      "cucumber (julienned, optional garnish)",
      "blanched soybean sprouts (optional)",
    ],
    steps: [
      "Heat neutral oil in a wok. Add ground pork and stir fry, breaking it up, until rendered and lightly browned.",
      "Push pork to the side. Add minced ginger and garlic, fry briefly, then add doubanjiang and sweet bean sauce. Stir until oil turns red and aromatic.",
      "Deglaze with Shaoxing wine. Add light and dark soy sauce, a pinch of sugar, and ground Sichuan peppercorn. Simmer until the sauce coats the pork.",
      "Boil round hand pulled noodles for 60 to 90 seconds, drain, and place in serving bowl.",
      "Top noodles with a generous spoon of the spicy minced pork sauce.",
      "Finish with a drizzle of house chili oil, chopped scallion, and optional julienned cucumber or soybean sprouts.",
      "Customer tosses everything together before eating.",
    ],
    allergens: ["wheat", "gluten", "soy", "sesame", "pork"],
  },
  {
    id: "braised_pork_belly_noodle",
    menuName: "Braised Pork Belly Noodle",
    category: "Dry Noodles",
    price: 17.99,
    noodleChoice: ["round (default)", "flat"],
    spiceOption: false,
    ingredients: [
      "hand_pulled_noodles_round",
      "braised_pork_belly (sliced or cubed, warmed in its braising liquid)",
      "small ladle of pork belly braising liquid (the 'light sauce' dressing)",
      "bok choy (blanched)",
      "scallion (chopped)",
      "white pepper",
      "small drizzle of sesame oil (optional)",
    ],
    steps: [
      "Boil round hand pulled noodles for 60 to 90 seconds, drain well, and place in serving bowl.",
      "Spoon a small ladle of strained braised pork belly sauce over the noodles as a light dressing. Toss to coat.",
      "Lay sliced or cubed braised pork belly across the top of the noodles, skin side up to show the glossy red braised color.",
      "Add blanched bok choy alongside the pork.",
      "Finish with a pinch of white pepper, chopped scallions, and an optional drop of sesame oil.",
    ],
    allergens: ["wheat", "gluten", "soy", "sesame", "pork"],
  },
  {
    id: "cumin_onion_lamb_stirred_noodle",
    menuName: "Cumin Onion Lamb Stirred Noodle",
    category: "Dry Noodles",
    price: 19.99,
    noodleChoice: ["flat (default)", "round"],
    spiceOption: true,
    ingredients: [
      "hand_pulled_noodles_flat",
      "lamb shoulder or leg (sliced thin against the grain)",
      "cornstarch (for velveting)",
      "Shaoxing wine",
      "light soy sauce",
      "ground cumin",
      "whole cumin seeds",
      "ground white pepper",
      "salt",
      "white onion (sliced)",
      "red bell pepper (sliced, optional)",
      "green chili pepper (sliced, for spicy)",
      "dried red chilies (for spicy)",
      "minced garlic",
      "minced ginger",
      "chili flakes (Xinjiang style coarse, for spicy)",
      "scallion (cut into 2 inch segments)",
      "cilantro (chopped, finish)",
      "neutral oil",
      "toasted sesame seeds (finish)",
    ],
    steps: [
      "Velvet sliced lamb in cornstarch, Shaoxing wine, a splash of light soy sauce, and white pepper. Rest 15 minutes.",
      "Boil flat hand pulled noodles for 90 seconds (slightly underdone, they will finish in the wok). Drain, toss with a little oil to prevent sticking.",
      "Heat a wok very hot with neutral oil. Sear lamb in a single layer until edges crisp and meat is just cooked. Remove.",
      "In the same wok add a touch more oil. Toast whole cumin seeds for 5 seconds, then add minced ginger, garlic, and dried red chilies (for the spicy version).",
      "Add sliced onion and any peppers. Stir fry on high heat until edges char slightly but vegetables stay crisp.",
      "Return lamb to the wok. Add the drained noodles, ground cumin, coarse chili flakes (spicy version), salt, and a splash of light soy sauce.",
      "Toss vigorously over high heat so noodles pick up the smoky wok hei and cumin coats every strand.",
      "Finish with scallion segments, chopped cilantro, and toasted sesame seeds. Plate immediately.",
    ],
    allergens: ["wheat", "gluten", "soy", "sesame"],
  },
  {
    id: "tomato_egg_noodle",
    menuName: "Tomato Egg Noodle",
    category: "Dry Noodles",
    price: 14.99,
    noodleChoice: ["round (default)", "flat"],
    spiceOption: false,
    ingredients: [
      "hand_pulled_noodles_round",
      "ripe tomatoes (large, cut into wedges)",
      "eggs (beaten with a splash of Shaoxing wine and pinch of salt)",
      "minced garlic",
      "ginger (small amount, grated)",
      "sugar (small pinch, balances the tomato acid)",
      "light soy sauce",
      "salt",
      "white pepper",
      "neutral oil",
      "scallion (chopped, finish)",
      "small drizzle of sesame oil (optional)",
    ],
    steps: [
      "Beat eggs with Shaoxing wine and a pinch of salt.",
      "Heat neutral oil in a wok until just shimmering. Pour in eggs and scramble softly until just set. Remove from wok.",
      "Add a touch more oil. Stir fry minced garlic and a little ginger briefly.",
      "Add tomato wedges. Cook on medium high heat, pressing the tomatoes so they break down and release their juice into a sauce, about 4 to 6 minutes.",
      "Season with a small pinch of sugar, light soy sauce, salt, and white pepper.",
      "Return the scrambled eggs to the wok and fold them gently into the tomato sauce.",
      "Boil round hand pulled noodles for 60 to 90 seconds, drain, place in bowl.",
      "Spoon the tomato egg sauce generously over the noodles. Finish with chopped scallion and optional drop of sesame oil.",
    ],
    allergens: ["wheat", "gluten", "soy", "egg", "sesame"],
  },
  {
    id: "diced_mushroom_chicken_tossed_noodle",
    menuName: "Diced Mushroom and Chicken Tossed Noodle",
    category: "Dry Noodles",
    price: null,
    priceNote: "Confirm price with kitchen",
    noodleChoice: ["round (default)", "flat"],
    spiceOption: false,
    ingredients: [
      "hand_pulled_noodles_round",
      "boneless skinless chicken thigh (small diced)",
      "fresh shiitake mushrooms (small diced)",
      "dried shiitake mushrooms (rehydrated, diced, soaking liquid reserved)",
      "king oyster or wood ear mushrooms (small diced, optional)",
      "cornstarch (for velveting chicken)",
      "Shaoxing wine",
      "light soy sauce",
      "dark soy sauce (small amount, for color)",
      "oyster sauce",
      "sugar (small pinch)",
      "white pepper",
      "minced ginger",
      "minced garlic",
      "scallion whites (chopped)",
      "scallion greens (chopped, finish)",
      "neutral oil",
      "small drizzle of sesame oil (finish)",
      "cornstarch slurry (to thicken sauce)",
    ],
    steps: [
      "Velvet diced chicken thigh in cornstarch, a splash of Shaoxing wine, light soy sauce, and white pepper. Rest 15 minutes.",
      "Rehydrate dried shiitake in warm water for 20 minutes. Reserve the dark soaking liquid for the sauce.",
      "Heat neutral oil in a wok. Sear diced chicken in a single layer until just golden on the edges. Remove.",
      "In the same wok, add a touch more oil. Stir fry minced ginger, garlic, and scallion whites briefly.",
      "Add all diced mushrooms (fresh shiitake, rehydrated shiitake, optional king oyster or wood ear). Stir fry on high heat until mushrooms release their moisture and start to brown, picking up wok hei.",
      "Return chicken to the wok. Add Shaoxing wine, light soy, a touch of dark soy for color, oyster sauce, a pinch of sugar, and a splash of the reserved shiitake soaking liquid.",
      "Simmer 1 to 2 minutes. Thicken with a cornstarch slurry until the sauce coats the chicken and mushrooms glossily.",
      "Boil round hand pulled noodles for 60 to 90 seconds, drain, and place in serving bowl.",
      "Spoon the chicken mushroom topping generously over the noodles.",
      "Finish with chopped scallion greens and a small drizzle of sesame oil.",
      "Customer tosses to combine before eating.",
    ],
    allergens: [
      "wheat",
      "gluten",
      "soy",
      "sesame",
      "shellfish (from oyster sauce)",
    ],
  },
  {
    id: "potato_chicken_noodle",
    menuName: "Potato Chicken Noodle",
    category: "Dry Noodles",
    price: null,
    priceNote: "Confirm price with kitchen",
    noodleChoice: ["flat (default, traditional)", "round"],
    spiceOption: true,
    ingredients: [
      "hand_pulled_noodles_flat",
      "bone in chicken (cut into bite size pieces, skin on) or boneless thigh",
      "Yukon gold or russet potato (cut into bite size chunks)",
      "green bell pepper (cut into chunks)",
      "red bell pepper (cut into chunks)",
      "white onion (cut into chunks)",
      "dried red chilies (Xinjiang style)",
      "Sichuan peppercorns",
      "star anise",
      "cassia bark",
      "bay leaves",
      "ginger (sliced)",
      "garlic (smashed)",
      "scallion whites (chopped)",
      "doubanjiang (Pixian fermented bean chili paste, small amount)",
      "Shaoxing wine",
      "light soy sauce",
      "dark soy sauce",
      "rock sugar",
      "beer (light lager) or water (for braising liquid)",
      "salt",
      "white pepper",
      "neutral oil",
      "cilantro (chopped, finish)",
    ],
    steps: [
      "Heat neutral oil in a wide wok or pot. Add rock sugar and let it melt to a light caramel.",
      "Add chicken pieces skin side down. Sear until golden and the caramel coats the chicken.",
      "Push chicken aside. Add dried red chilies, Sichuan peppercorns, star anise, cassia bark, bay leaves, sliced ginger, smashed garlic, and scallion whites. Toast briefly until fragrant.",
      "Add doubanjiang and stir until the oil turns red.",
      "Deglaze with Shaoxing wine. Add light soy sauce, dark soy sauce for color, and pour in enough light beer (or water) to nearly cover the chicken.",
      "Add potato chunks. Bring to a boil, then reduce to a simmer. Cover and cook 20 to 25 minutes until chicken is tender and potatoes are creamy but still hold their shape.",
      "Uncover. Add bell pepper and onion chunks. Stir fry into the braise for 3 to 4 minutes until peppers are just tender but still bright.",
      "Adjust seasoning with salt and white pepper. The sauce should be reduced, glossy, and intensely savory with a slow building heat.",
      "Boil flat hand pulled noodles for 90 to 120 seconds, drain, and place in a large serving bowl or platter.",
      "Spoon the chicken, potato, and pepper braise generously over the noodles, including plenty of the dark red sauce.",
      "Finish with chopped cilantro. Traditionally served family style on a large platter.",
    ],
    allergens: ["wheat", "gluten", "soy", "sesame"],
  },
  {
    id: "house_special_beef_bone_noodle_soup",
    menuName: "House Special Beef Bone Noodle Soup",
    category: "Noodle Soup",
    price: 20.99,
    noodleChoice: ["round (default)", "flat"],
    spiceOption: true,
    ingredients: [
      "hand_pulled_noodles_round",
      "beef_bone_broth (hot)",
      "braised_beef_shank (sliced thick)",
      "bone in beef section with marrow (warmed in master sauce)",
      "bok choy (blanched)",
      "scallion (chopped)",
      "cilantro (chopped)",
      "white pepper",
      "salt (to adjust)",
      "house_chili_oil (for spicy version, served on top or on the side)",
      "pickled mustard greens (small garnish, optional)",
    ],
    steps: [
      "Boil round hand pulled noodles for 60 to 90 seconds, drain, and place in a large serving bowl.",
      "Ladle very hot beef bone broth over the noodles, filling about three quarters of the bowl. Adjust seasoning with salt and white pepper.",
      "Lay thick slices of braised beef shank across one side of the noodles. Place the bone in beef section with marrow on top, marrow side up.",
      "Add blanched bok choy on the opposite side.",
      "Finish with chopped scallion, cilantro, and a small mound of pickled mustard greens if used.",
      "For the spicy version, ladle house chili oil over the top so it floats as a red layer on the clear broth, or serve on the side.",
    ],
    allergens: ["wheat", "gluten", "soy", "sesame"],
  },
  {
    id: "braised_beef_noodle_soup",
    menuName: "Braised Beef Noodle Soup",
    category: "Noodle Soup",
    price: 18.99,
    noodleChoice: ["round (default)", "flat"],
    spiceOption: false,
    ingredients: [
      "hand_pulled_noodles_round",
      "braised_beef_shank (chunked)",
      "rich red braising broth (master sauce thinned with beef bone broth)",
      "doubanjiang (small amount, for depth and red color)",
      "tomato paste (small amount, for body)",
      "star anise",
      "cassia bark",
      "ginger",
      "scallion (whites for broth, greens for garnish)",
      "Shaoxing wine",
      "rock sugar (small amount)",
      "bok choy (blanched)",
      "cilantro (chopped)",
      "white pepper",
    ],
    steps: [
      "Build the soup base: combine strained master sauce braising liquid with beef bone broth in a pot. Add a small amount of doubanjiang and tomato paste for depth and color. Refresh aromatics with star anise, cassia bark, ginger, and scallion whites. Simmer 20 minutes, then strain.",
      "Add chunks of braised beef shank to the broth and warm through.",
      "Boil round hand pulled noodles for 60 to 90 seconds, drain, place in serving bowl.",
      "Ladle the hot aromatic broth and beef chunks over the noodles.",
      "Add blanched bok choy on the side.",
      "Garnish with chopped scallion greens, cilantro, and a small pinch of white pepper.",
    ],
    allergens: ["wheat", "gluten", "soy", "sesame"],
  },
  {
    id: "pickled_cabbage_beef_noodle_soup",
    menuName: "Pickled Cabbage Beef Noodle Soup",
    category: "Noodle Soup",
    price: 18.99,
    noodleChoice: ["round (default)", "flat"],
    spiceOption: false,
    spiceDefault: "mildly spicy",
    ingredients: [
      "hand_pulled_noodles_round",
      "braised_beef_shank (sliced)",
      "beef_bone_broth",
      "Sichuan pickled mustard greens (suan cai, rinsed and chopped)",
      "pickled chili peppers (chopped, optional for heat)",
      "ginger (julienned)",
      "garlic (sliced)",
      "scallion whites (smashed)",
      "Shaoxing wine",
      "white pepper",
      "neutral oil",
      "scallion greens (chopped, finish)",
      "cilantro (chopped, finish)",
      "house_chili_oil (optional drizzle)",
    ],
    steps: [
      "In a small pot heat neutral oil. Stir fry julienned ginger, sliced garlic, and scallion whites until fragrant.",
      "Add chopped pickled mustard greens (and chopped pickled chilies for more heat). Stir fry 1 to 2 minutes to release the tangy aroma.",
      "Deglaze with Shaoxing wine, then pour in beef bone broth. Simmer 10 minutes so the broth turns tangy and aromatic.",
      "Add sliced braised beef and warm through. Adjust with white pepper. Usually no extra salt is needed because the pickles bring saltiness.",
      "Boil round hand pulled noodles for 60 to 90 seconds, drain, place in bowl.",
      "Ladle the tangy broth, beef, and pickled greens over the noodles.",
      "Finish with chopped scallion greens, cilantro, and an optional drizzle of house chili oil.",
    ],
    allergens: ["wheat", "gluten", "soy", "sesame"],
  },
  {
    id: "tomato_beef_noodle_soup",
    menuName: "Tomato Beef Noodle Soup",
    category: "Noodle Soup",
    price: 18.99,
    noodleChoice: ["round (default)", "flat"],
    spiceOption: false,
    ingredients: [
      "hand_pulled_noodles_round",
      "braised_beef_shank (chunked) or stewed beef chuck",
      "beef_bone_broth",
      "ripe tomatoes (cut into wedges)",
      "tomato paste (small amount, for color and body)",
      "ginger (sliced)",
      "scallion whites (smashed)",
      "garlic (smashed)",
      "Shaoxing wine",
      "light soy sauce",
      "rock sugar (small pinch)",
      "salt",
      "white pepper",
      "neutral oil",
      "scallion greens (chopped, finish)",
      "cilantro (chopped, finish)",
      "bok choy (blanched, optional)",
    ],
    steps: [
      "In a pot heat neutral oil. Fry ginger, scallion whites, and garlic until fragrant.",
      "Add tomato wedges and a small spoon of tomato paste. Stir fry until the tomatoes break down and the oil turns red, about 5 minutes.",
      "Deglaze with Shaoxing wine. Pour in beef bone broth. Add a small pinch of rock sugar to round out acidity and a splash of light soy sauce for depth.",
      "Add chunks of beef (braised shank or pre stewed chuck). Simmer 15 to 20 minutes until the broth is sweet, tangy, and red.",
      "Season with salt and white pepper.",
      "Boil round hand pulled noodles for 60 to 90 seconds, drain, place in bowl.",
      "Ladle the tomato beef broth over the noodles, distributing beef and tomato chunks evenly.",
      "Add blanched bok choy if using. Finish with chopped scallion greens and cilantro.",
    ],
    allergens: ["wheat", "gluten", "soy", "sesame"],
  },
  {
    id: "golden_sour_spicy_lamb_noodle_soup",
    menuName: "Golden Sour and Spicy Lamb Noodle Soup",
    category: "Noodle Soup",
    price: 18.99,
    noodleChoice: ["round (default)", "flat"],
    spiceOption: false,
    spiceDefault: "sour and spicy",
    ingredients: [
      "hand_pulled_noodles_round",
      "lamb shoulder or lamb leg (sliced thin or cut into bite size pieces)",
      "yellow pickled peppers (huang la jiao, blended into a paste, for the signature golden color)",
      "fresh yellow chili peppers (or ají amarillo style yellow chilies, chopped)",
      "ginger (julienned)",
      "garlic (minced)",
      "scallion whites (smashed)",
      "Shaoxing wine",
      "white pepper",
      "salt",
      "chicken or light beef broth (clear, as base)",
      "white vinegar or rice vinegar (small amount, for sour brightness)",
      "neutral oil",
      "cilantro (chopped, finish)",
      "scallion greens (chopped, finish)",
    ],
    steps: [
      "Blend yellow pickled peppers with a bit of their brine into a smooth golden paste.",
      "Heat neutral oil in a pot. Fry julienned ginger, minced garlic, and scallion whites briefly.",
      "Add the yellow pickled pepper paste and chopped fresh yellow chilies. Stir fry 1 to 2 minutes until the oil turns bright golden yellow and the kitchen smells tangy and pungent.",
      "Add sliced lamb and quickly sear with the paste so the lamb picks up the color and flavor.",
      "Deglaze with Shaoxing wine, then pour in clear chicken or light beef broth. Simmer 8 to 10 minutes until the lamb is tender and the broth is a vivid yellow.",
      "Adjust with a small splash of vinegar for sour brightness, salt, and white pepper.",
      "Boil round hand pulled noodles for 60 to 90 seconds, drain, place in serving bowl.",
      "Ladle the golden lamb broth over the noodles.",
      "Finish with chopped cilantro and scallion greens.",
    ],
    allergens: ["wheat", "gluten", "soy", "sesame"],
  },
  {
    id: "stew_lamb_carrots_noodle",
    menuName: "Stew Lamb and Carrots Noodle",
    category: "Noodle Soup",
    price: null,
    priceNote: "Confirm price with kitchen",
    noodleChoice: ["round (default)", "flat"],
    spiceOption: false,
    spiceDefault: "mild, warming",
    ingredients: [
      "hand_pulled_noodles_round",
      "lamb shoulder or lamb shank (cut into bite size pieces, bone in pieces optional for richer broth)",
      "carrots (peeled and cut into thick oblique chunks)",
      "white radish or daikon (optional, cut into chunks)",
      "ginger (sliced thick)",
      "scallion whites (smashed)",
      "garlic (whole cloves, smashed)",
      "star anise",
      "cassia bark",
      "bay leaves",
      "dried tangerine peel (chen pi, small piece)",
      "Sichuan peppercorns (small amount, in a spice bag)",
      "Shaoxing wine",
      "light soy sauce",
      "rock sugar (small pinch)",
      "salt",
      "white pepper",
      "neutral oil",
      "water or light chicken stock",
      "cilantro (chopped, finish)",
      "scallion greens (chopped, finish)",
      "house_chili_oil (optional, on the side)",
    ],
    steps: [
      "Blanch lamb pieces in boiling water for 2 minutes to remove gaminess and scum. Drain and rinse.",
      "Heat neutral oil in a heavy pot. Sear blanched lamb pieces until lightly golden on the edges.",
      "Add sliced ginger, smashed scallion whites, and whole garlic cloves. Stir until fragrant.",
      "Add star anise, cassia bark, bay leaves, dried tangerine peel, and a small spice bag of Sichuan peppercorns.",
      "Deglaze with Shaoxing wine. Add light soy sauce and a small pinch of rock sugar.",
      "Pour in water or light chicken stock to cover the lamb by 2 inches. Bring to a boil, skim impurities, then reduce to a low simmer.",
      "Cover and stew for 1 to 1.5 hours until the lamb is fork tender and the broth is fragrant and slightly cloudy from the rendered collagen.",
      "Add carrot chunks (and optional daikon) in the last 25 minutes of cooking so they become tender but still hold shape and absorb the broth.",
      "Remove the spice bag. Adjust seasoning with salt and white pepper. The broth should be warming, savory, lightly sweet from the carrots, and gently aromatic with no harsh spice.",
      "Boil round hand pulled noodles for 60 to 90 seconds, drain, and place in a large serving bowl.",
      "Ladle the lamb, carrots, and aromatic broth generously over the noodles.",
      "Finish with chopped cilantro and scallion greens. Serve house chili oil on the side for guests who want heat without altering the dish.",
    ],
    allergens: ["wheat", "gluten", "soy", "sesame"],
  },
  {
    id: "sichuan_spicy_tofu_soup",
    menuName: "Sichuan Spicy Tofu Noodle Soup",
    category: "Noodle Soup",
    price: null,
    priceNote: "Confirm price with kitchen",
    spiceOption: false,
    spiceDefault: "spicy and numbing (mala)",
    ingredients: [
      "soft or silken tofu (cubed, blanched briefly in lightly salted water to firm)",
      "ground pork or ground beef (small amount, for depth)",
      "Pixian doubanjiang (fermented broad bean chili paste)",
      "douchi (fermented black beans, rinsed and roughly chopped)",
      "house_chili_oil",
      "dried red chilies",
      "Sichuan peppercorns (whole, for the broth)",
      "ground roasted Sichuan peppercorn (for finishing, the mala kick)",
      "minced garlic",
      "minced ginger",
      "scallion whites (chopped)",
      "Shaoxing wine",
      "light soy sauce",
      "dark soy sauce (small amount, for color)",
      "sugar (small pinch)",
      "white pepper",
      "salt",
      "chicken stock or light pork stock",
      "cornstarch slurry (to thicken)",
      "neutral oil",
      "scallion greens (finely chopped, finish)",
      "cilantro (chopped, optional finish)",
    ],
    steps: [
      "Cube soft tofu into bite size pieces. Bring a pot of lightly salted water to a gentle simmer and blanch the tofu cubes for 2 minutes to firm them up and remove any raw bean flavor. Drain gently and set aside.",
      "Heat neutral oil in a wok over medium heat. Add a small amount of ground pork or beef and stir fry until fully rendered and lightly crisp.",
      "Add minced ginger, minced garlic, scallion whites, and dried red chilies. Stir briefly until fragrant.",
      "Add doubanjiang and chopped douchi. Fry slowly until the oil turns deep red and aromatic, about 1 minute. This step is essential for proper depth.",
      "Add a small amount of whole Sichuan peppercorns and toast briefly.",
      "Deglaze with Shaoxing wine. Pour in chicken or light pork stock to make a soup volume (more liquid than a typical mapo tofu).",
      "Season with light soy sauce, a small amount of dark soy for color, a pinch of sugar, white pepper, and salt to taste. Simmer 5 minutes so the broth turns red, glossy, and deeply savory.",
      "Gently slide the blanched tofu cubes into the broth. Simmer 3 to 4 minutes, nudging the pot rather than stirring so the tofu stays intact.",
      "Thicken the broth lightly with a cornstarch slurry in 2 stages so it clings to the tofu without becoming gluey.",
      "Drizzle a final round of house chili oil over the top for color and aroma.",
      "Transfer to a serving bowl. Finish with a generous dusting of ground roasted Sichuan peppercorn (this is what creates the numbing mala finish, must be added at the end), chopped scallion greens, and optional cilantro.",
      "Serve hot. Best eaten with steamed rice on the side.",
    ],
    allergens: [
      "soy",
      "wheat (from soy sauce and doubanjiang)",
      "sesame",
      "pork (if using ground pork) or beef (if using ground beef)",
    ],
  },
  {
    id: "tomato_beef_over_rice",
    menuName: "Tomato Beef over White Rice",
    category: "Rice",
    price: 16.99,
    spiceOption: false,
    ingredients: [
      "steamed jasmine or medium grain white rice",
      "beef chuck or beef shank (cut into bite size pieces, pre stewed until tender)",
      "ripe tomatoes (cut into wedges)",
      "tomato paste (small amount)",
      "ginger (sliced)",
      "garlic (smashed)",
      "scallion whites (smashed)",
      "Shaoxing wine",
      "light soy sauce",
      "dark soy sauce (small amount, for color)",
      "rock sugar (small pinch)",
      "salt",
      "white pepper",
      "neutral oil",
      "scallion greens (chopped, finish)",
      "cornstarch slurry (optional, to thicken)",
    ],
    steps: [
      "Pre stew beef chunks until fork tender (around 1.5 to 2 hours with ginger, scallion, and Shaoxing wine).",
      "Heat oil in a wok. Fry ginger, garlic, and scallion whites briefly.",
      "Add tomato wedges and a touch of tomato paste. Stir fry until tomatoes break down and oil turns red.",
      "Add tender stewed beef along with a ladle of its cooking liquid. Season with Shaoxing wine, light soy, a touch of dark soy, rock sugar, salt, and white pepper. Simmer 5 minutes.",
      "Thicken slightly with a cornstarch slurry if desired so the sauce coats the rice.",
      "Plate a generous mound of steamed white rice. Spoon the tomato beef stew over half the rice so the other half stays white.",
      "Finish with chopped scallion greens.",
    ],
    allergens: ["soy", "wheat (from soy sauce)"],
  },
  {
    id: "braised_pork_over_rice",
    menuName: "Braised Pork over White Rice",
    category: "Rice",
    price: 16.99,
    spiceOption: false,
    ingredients: [
      "steamed jasmine or medium grain white rice",
      "braised_pork_belly (cubed, with its braising sauce)",
      "ladle of pork braising liquid",
      "bok choy (blanched) or",
      "Chinese pickled mustard greens (suan cai or zha cai, chopped)",
      "scallion (chopped)",
      "soft boiled or tea egg (optional, common Taiwanese style addition)",
      "fried shallots (optional, garnish)",
      "white pepper",
    ],
    steps: [
      "Plate a generous mound of steamed white rice.",
      "Top the rice with cubed braised pork belly and a ladle of its glossy braising liquid so it soaks into the rice.",
      "Place blanched bok choy on one side, or a small mound of chopped pickled mustard greens for a tangy counterpoint.",
      "Optionally add a halved soft boiled or tea egg.",
      "Finish with chopped scallion, a sprinkle of fried shallots if using, and a pinch of white pepper.",
    ],
    allergens: ["soy", "wheat (from soy sauce)", "egg (if egg is added)"],
  },
  {
    id: "handmade_fragrance_lemon_tea",
    menuName: "Handmade Fragrance Lemon Tea",
    category: "Beverages",
    price: 6.99,
    ingredients: [
      "fresh lemons (whole, sliced and muddled)",
      "jasmine green tea or green tea (brewed strong and chilled)",
      "honey or simple syrup",
      "ice",
      "small pinch of sea salt (optional, brightens flavor)",
      "fresh mint (optional)",
    ],
    steps: [
      "Brew jasmine or green tea strong, then chill.",
      "Slice fresh lemon into thin rounds. Muddle a few slices in the bottom of a serving cup with honey or simple syrup to release the oils from the rind.",
      "Fill cup with ice. Pour chilled tea over the top.",
      "Optional pinch of sea salt and fresh mint sprig.",
      "Shake or stir vigorously at the counter (the 'shake shake' presentation) before serving.",
      "Serve with extra lemon slices floating on top.",
    ],
    allergens: [],
  },
  {
    id: "coffee_meets_milk_tea",
    menuName: "Coffee Meets Milk Tea",
    category: "Beverages",
    price: 6.99,
    ingredients: [
      "strong brewed black coffee (espresso or dark drip)",
      "strong brewed Hong Kong style black tea (Ceylon and pu erh blend is traditional)",
      "sweetened condensed milk or evaporated milk plus sugar",
      "ice (for cold version) or hot water topping (for hot version)",
    ],
    steps: [
      "Brew strong black coffee and strong Hong Kong style black tea separately.",
      "In a serving cup combine roughly 3 parts tea to 7 parts coffee (or to house ratio).",
      "Sweeten with sweetened condensed milk, or evaporated milk plus sugar to taste.",
      "Stir thoroughly until fully combined.",
      "For cold version, pour over ice. For hot version, serve immediately.",
      "Optional foam or sprinkle of cocoa is not traditional but can be requested.",
    ],
    allergens: ["dairy"],
  },
  {
    id: "soft_drinks",
    menuName: ["Coke", "Diet Coke", "Sprite"],
    category: "Beverages",
    price: 2.99,
    ingredients: ["canned or bottled soda (purchased, not made in house)"],
    steps: [
      "Serve chilled in can or bottle, or pour over ice in a cup with a straw.",
    ],
    allergens: [],
    notes: "Purchased product. Not made in house.",
  },
  {
    id: "peach_sparkling_water",
    menuName: "Peach Sparkling Water",
    category: "Beverages",
    price: 3.99,
    ingredients: [
      "bottled or canned peach flavored sparkling water (purchased, not made in house)",
    ],
    steps: [
      "Serve chilled in can or bottle, or pour over ice in a glass.",
    ],
    allergens: [],
    notes: "Purchased product. Not made in house.",
  },
];

// Cross-cutting allergen summary the chef wants the assistant to use as a
// quick reference when answering "is X safe" questions.
export const GLOBAL_ALLERGEN_SUMMARY = {
  wheat_gluten:
    "Present in all noodles, dumpling wrappers, wonton wrappers, scallion pancakes, and any dish using soy sauce, doubanjiang, oyster sauce, or hoisin.",
  soy: "Present in all dishes using soy sauce, hoisin, doubanjiang, douchi, sweet bean sauce, tofu (including silken tofu in spicy tofu soup), tofu skin (yuba), or master braise.",
  sesame:
    "Present in any dish using sesame oil, sesame seeds, or house chili oil (which contains sesame seeds).",
  egg: "Present in popcorn chicken marinade, tomato egg noodle, optional tea egg with braised pork rice.",
  dairy: "Only in Coffee Meets Milk Tea (condensed or evaporated milk).",
  shellfish:
    "Present in any dish using oyster sauce (currently the diced mushroom and chicken tossed noodle).",
  pork: "Used in dumplings, wontons, minced pork noodle, braised pork belly dishes, and optionally in Sichuan spicy tofu soup.",
  lamb: "Used in cumin lamb noodle, golden sour and spicy lamb noodle soup, and stewed lamb and carrots noodle soup.",
  beef: "Used in all braised beef dishes, beef bone broth, tomato beef dishes, cold cut beef, and optionally in Sichuan spicy tofu soup.",
  chicken:
    "Used in popcorn chicken, diced mushroom and chicken tossed noodle, and potato chicken noodle.",
};

// Kitchen rules the assistant uses when guests ask about customization or
// dietary swaps. Doubanjiang and pickled peppers are core to specific
// dishes, so the model is told it can lower heat but not remove these.
export const CUSTOMIZATION_RULES = {
  spice_levels:
    "When a customer asks for 'less spicy' or 'no spice,' the kitchen can reduce or omit house chili oil and dry chili flakes. However doubanjiang (in numbing minced pork, potato chicken noodle, and Sichuan spicy tofu soup), douchi and ground Sichuan peppercorn (in Sichuan spicy tofu soup), and pickled peppers (in golden sour and spicy lamb) are core to those dishes and cannot be removed without changing the dish identity. Stewed lamb and carrots noodle is naturally mild, chili oil is served on the side.",
  noodle_choice:
    "Round vs flat is interchangeable on all noodle dishes. Default style is listed per dish. Potato chicken noodle traditionally uses flat noodles (da pan ji style).",
  vegetarian_substitutions:
    "Most meat dishes cannot be made vegetarian because the broths and braising liquids contain meat. Garlic Cucumber, Yuba with Celery Salad, Chili Oil Potato Salad, and Tomato Egg Noodle are the closest vegetarian friendly options (confirm with kitchen on broth contact). Sichuan spicy tofu soup is not vegetarian by default because it uses ground meat and meat stock, though it could potentially be made vegetarian on request by substituting vegetable stock and omitting the meat.",
  gluten_free:
    "No dish is currently gluten free because all noodles, wrappers, soy sauce, doubanjiang, and oyster sauce contain wheat.",
  shellfish_allergy:
    "The diced mushroom and chicken tossed noodle contains oyster sauce. Customers with shellfish allergy should be steered away from this dish or ask if the kitchen can prepare it without oyster sauce.",
  add_ons:
    "Currently formal add ons only apply to Regular Chili Oil Flat Noodle: tomato eggs +$2, ground pork +$3, braised beef +$4.",
  missing_prices:
    "Chili Oil Potato Salad, Diced Mushroom and Chicken Tossed Noodle, Potato Chicken Noodle, Stew Lamb and Carrots Noodle, and Sichuan Spicy Tofu Noodle Soup do not have prices in this dataset yet. When a customer asks the price for one of these dishes, say you will confirm with the kitchen rather than guess.",
};

// Bundle for the system prompt. Keeping this as a single export makes the
// system prompt builder easy to read and lets us cache the whole knowledge
// block as one ephemeral cache entry.
export const RECIPE_KNOWLEDGE = {
  notes_for_ai:
    "Detailed chef-authored composition for every dish. House components (noodles, chili oil, braised meats, master sauce, beef bone broth, dumpling wrappers, scallion pancakes) are defined once and referenced by ID inside each recipe. When a guest asks about ingredients, allergens, spice, or customization, expand the referenced components and union their allergens with the recipe's top-level allergens. Match recipes to menu items via menuName (exact string match against MenuItem.name).",
  house_components: HOUSE_COMPONENTS,
  recipes: RECIPES,
  global_allergen_summary: GLOBAL_ALLERGEN_SUMMARY,
  customization_rules: CUSTOMIZATION_RULES,
};
